parser: "@typescript-eslint/parser"
extends:
      - "airbnb"
      - "airbnb-typescript"

env:
      browser: true
      node: true
      es6: true

plugins:
      - "@typescript-eslint"
      - "react"

parserOptions:
      project: "./tsconfig.json"
      ecmaFeatures:
            jsx: true
      ecmaVersion: 2018
      sourceType: "module"

rules:
      react/jsx-filename-extension: [1, { "extensions": [".tsx"] }]
      react/prop-types: "off"