image: node

stages:
  - lint
  - build

eslint:
  stage: lint

  script:
    - npm i -g eslint
    - npm i eslint-config-airbnb
    - npx install-peerdeps eslint-config-airbnb
    - npm install --only=prod
    - npm run eslint-fix
# This code essentially uses Docker to pull node and uses node to install/configure eslint and run the eslint script

variables:
  NODE_ENV: 'pipeline'

preprod_gatsby_build:
  stage: build

  script:
    - npm i
    - npm run build
# This code will try to run gatsby build to make sure your code is deployable.
