image: node

stages: 
  - lint

eslint:
  stage: lint

  script:
    - npm i -g eslint
    - npm install eslint-config-airbnb --save-dev
    - npx install-peerdeps --dev eslint-config-airbnb
    - npm --prefix client install client
    - eslint --ext js,jsx .
